Bugfix
OpenWaterAnalytics/EPANET pull request #744
Opened 2023-08-02 06:54 UTC by 0tkl

We're going to use EPANET in some serious scenarios which requires passing the static analyzer.

We fixed all problems reported in gcc static analyzer `-fanalyzer`, and all but problems in "Unused code" category in Clang analyzer `scan-build`.

2023-08-03 11:52 UTC, LRossman requested changes
Please address review comments for changes made to project.c. The changes made to other files are OK.

2023-08-03 11:52 UTC, LRossman commented on src/project.c
> +        newPtr = realloc(vertices->X, vertices->Capacity * sizeof(double));
Use of `newPtr `is not needed since original line 582 tests if either `vertices->X` or` vertices->Y` is `NULL`.

2023-08-03 11:52 UTC, LRossman commented on src/project.c
>      if (n2 > n) n2 = n;
I don't see what is wrong with the original code in lines 1382 to 1385.

2023-08-03 11:52 UTC, LRossman commented on src/project.c
>      strncpy(*s1, s2, n2+1);
New lines 1410 to 1415 are unnecessary if we simply replace the original line 1401 with:
```
    if (*s1) strncpy(*s1, s2, n2+1);
```

2023-08-04 18:05 UTC, 0tkl commented
Changes:
1. In `addlinkvertex()`, when realloc failed and pointer pointed to NULL, free the old array.  
(The previous version of my code just leave the pointer unchanged when realloc failed, due to my misconception of its expected behavior.)
2. Apply your comments in `xstrcpy()`.
3. In `ENR_getNetSize()`, use the way that is consistent with other functions in `epanet_output.c` to handle allocation failures.

2023-08-07 16:04 UTC, LRossman reviewed
I re-worked `addlinkvertex `in project.c to leave the current X and Y vertex coordinates unchanged in case their re-allocation fails, since it allows the other vertex routines like EN_getvertex and EN_setvertex to still work. See if you agree with it:

```
{
    static int CHUNKSIZE = 5;
    int n, newCapacity;
    Pvertices vertices;
    double *newX, *newY;

    vertices = link->vertices;
    if (vertices == NULL)
    {
        vertices = (struct Svertices *) malloc(sizeof(struct Svertices));
        if (vertices == NULL) return 101;
        vertices->Npts = 0;
        vertices->Capacity = 0;
        vertices->X = NULL;
        vertices->Y = NULL;
        link->Vertices = vertices;
    }
    if (vertices->Npts >= vertices->Capacity)
    {
        newCapacity = vertices->Capacity + CHUNKSIZE;
        newX = realloc(vertices->X, newCapacity * sizeof(double));
        newY = realloc(vertices->Y, newCapacity * sizeof(double));
        if (newX == NULL || newY == NULL)
        {
            free(newX);
            free(newY);
            return 101;
        }
        else
        {
            vertices->Capacity = newCapacity;
            vertices->X = newX;
            vertices->Y = newY;
        }
    }
    n = vertices->Npts;
    vertices->X[n] = x;
    vertices->Y[n] = y;
    vertices->Npts++;
    return 0;    
}
```

2023-08-10 14:10 UTC, LRossman requested changes
I see you added a new `setlinkvertices `function to avoid successive calls to `addlinkvertex `in `EN_setvertices`. I would prefer that you remove the new function and keep the current version of `EN_setvertices`. Because most links will have 5 (= `CHUNKSIZE`) or fewer vertices, the overhead from repeated calls to `addlinkvertex `will be small since a memory reallocation won't be needed.

2023-08-10 14:44 UTC, 0tkl commented
OK, I reverted it.

2023-08-10 15:44 UTC, merged